version: "3"
services:
  rabbit_node0:
    image: pivotalrabbitmq/rabbitmq-stream
    ports:
      - "15672:15672"
      - "5552:5552"
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost advertised_port 5552
